### ISSUE TITLE
Make it possible to hide the hint bar on the bottom of the screen

### ISSUE THREAD

**Issue by koraa** [dkaslovsky/nav#1]
Thank you for writing this tool! I think it would be very useful if the bottom bar could be hidden.

**Comment by dkaslovsky** [comment]
Thanks for the kind words and the comment! That should be doable and I'll see about including it in the next release, which I'm hoping to get to in the next few days. Thanks again.

**Comment by dkaslovsky** [comment]
This feature has been released as part of v1.1.0. Thanks again for the input!
